### ISSUE TITLE
Transaction Tracing issue: not working

### ISSUE THREAD

**Issue by Unitech** [keymetrics/keymetrics-support#122]
Tracing was not working at first with pm2-docker and an ecosystem with `trace:true`

The user had to run `docker exec -it [container] pm2 reload [app name] --trace` to make it working

**Comment by Unitech** [comment]
+1 bug with pm2-docker with trace:true

**Comment by Unitech** [comment]
+1 {"msg":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures  https://keymetrics.zendesk.com/agent/tickets/1407

**Comment by Unitech** [comment]
+1 restify 6 is not supported ? /agent/tickets/1626

**Comment by Unitech** [comment]
+1 TypeError: Cannot redefine property: stream -
at Function.defineProperty ()
at RedisClient.create_stream_trace (/home/ubuntu/node_modules/vxx/src/plugins/plugin-redis.js:36:16)
at RedisClient.create_stream_trace [as create_stream] (/usr/local/lib/node_modules/pm2/node_modules/vxx/src/plugins/plugin-redis.js:44:28)
at new RedisClient (/home/ubuntu/node_modules/redis/index.js:161:10)
at exports.createClient (/home/ubuntu//node_modules/redis/index.js:1081:12)
at createClientTrace (/home/ubuntu/node_modules/vxx/src/plugins/plugin-redis.js:24:33)
at createClientTrace (/usr/local/lib/node_modules/pm2/node_modules/vxx/src/plugins/plugin-redis.js:24:33)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Function.Module_load (/usr/local/lib/node_modules/pm2/node_modules/vxx/src/trace-plugin-loader.js:168:33)
at Function. (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:94:21)
at Function.Module_load (/home/ubuntu/node_modules/vxx/src/trace-plugin-loader.js:168:33)

**Comment by vmarchaud** [comment]
+1 Not working with Sails.JS

**Comment by vmarchaud** [comment]
+1: Need to keep trace history across restart

**Comment by samous** [comment]
Hello, any news about trace issue ?

**Comment by alexandretok** [comment]
Same issue here...

**Comment by robin-monnier** [comment]
Doesn't work on bucket 5a904a8b85579d79f9168562

**Comment by robin-monnier** [comment]
Doesn't work on bucket 5abcafd256f166e50a98cc48

With Koa 2.x

**Comment by robin-monnier** [comment]
5ae2c1edaca6cbc604432700

#2296
