### ISSUE TITLE
Module: pm2 mongo db error

### ISSUE THREAD

**Issue by rmonnier** [keymetrics/keymetrics-support#179]
A user get an exception with pm2 mongo db module, making the module only monitoring CPU and MEM. All other fields shows N/A.

Ticket: #2056
5a678f7e1b310d5884d7f85f

```
PM2        | Stopping app:pm2-server-monit id:0
PM2        | App [pm2-server-monit] with id [0] and pid [24600], exited with code [0] via signal [SIGINT]
PM2        | pid=24600 msg=process killed
PM2        | Stopping app:pm2-mongodb id:1
PM2        | App [pm2-mongodb] with id [1] and pid [24608], exited with code [0] via signal [SIGINT]
PM2        | pid=24608 msg=process killed
1|pm2-mong | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|pm2-mong | TypeError: db.admin is not a function
1|pm2-mong |     at /root/.pm2/modules/pm2-mongodb/node_modules/pm2-mongodb/lib/stats/client.js:54:17
1|pm2-mong |     at <anonymous>
1|pm2-mong |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by vmarchaud** [comment]
https://github.com/pm2-hive/pm2-mongodb#configuration
```
NODE : User should have access to admin database to query statistics
```
