### ISSUE TITLE
can't install pm2 profiler

### ISSUE THREAD

**Issue by nxn-bwv21** [keymetrics/keymetrics-support#201]
i command `sudo pm2 install profiler` and got next error messages.

```
[PM2][Module] Installing module profiler
[PM2][Module] Calling [NPM] to install v8-profiler-node8 ...

> v8-profiler-node8@6.0.0 preinstall /usr/local/lib/node_modules/pm2/node_modules/v8-profiler-node8
> node -e 'process.exit(0)'


> v8-profiler-node8@6.0.0 install /usr/local/lib/node_modules/pm2/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.4.0-1061-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/lib/node_modules/pm2/node_modules/v8-profiler-node8
gyp ERR! node -v v9.6.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:933:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.4.0-1061-aws
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/pm2/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/pm2/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v9.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.2
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@6.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-07-04T01_03_42_851Z-debug.log
[PM2][Module][ERROR] v8-profiler-node8 installation has FAILED (checkout previous logs)
[PM2][ERROR] Module install failed
```

i tried `sudo chown -R myaccount.myaccount /usr/local/lib/node_modules/`  but didn't work.

i use aws ec2 and os infomation is here.
```
grep . /etc/*-release
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.3 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.3 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

how can i solve this problem?

**Comment by vmarchaud** [comment]
Hello,

You can use the new pm2 version (3.0) with node > 8 and the profiling will be available out of the box

**Comment by grinry** [comment]
I still get same error with pm2 version 3.0.3 and node 8.9

**Comment by vmarchaud** [comment]
I meant that if you use node 10 and pm2 3, you will not need to install `v8-profiler-node8`, or you could use node 8 and add `FORCE_INSPECTOR=1` in your environment to enable it.
