### ISSUE TITLE
Exception is seen by email but not when I log into the account

### ISSUE THREAD

**Issue by nukulb** [keymetrics/keymetrics-support#53]
My account is under nukul@mavencare.com

the following exception was seen by email but when I log into the account its not visible

```
A new exception has been thrown
Server: prod1
App: app
Msg:
Error
    at Object.exports.(anonymous function) [as error] (/home/maven/dist/server/components/logger/index.js:58:23)
    at handleError (/home/maven/dist/server/api/caregiver/caregiver.controller.js:421:12)
    at Promise. (/home/maven/dist/server/api/caregiver/caregiver.controller.js:353:24)
    at Promise. (/home/maven/dist/node_modules/mongoose/node_modules/mpromise/lib/promise.js:172:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/home/maven/dist/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.reject (/home/maven/dist/node_modules/mongoose/node_modules/mpromise/lib/promise.js:111:15)
    at Promise.error (/home/maven/dist/node_modules/mongoose/lib/promise.js:95:15)
    at process._tickDomainCallback (node.js:463:13)
```

**Comment by jorge-d** [comment]
Hi,

I guess you don't you have any filter enabled (topbar) ? Do you have any Javascript error when going to the exception page? Are you sure that you did not pressed "set as fixed" by accident?

Thanks,

**Comment by Unitech** [comment]
fixed!
